import jsPDF from 'jspdf';

// ─── Color Palette (MOMternal Brand) ──────────────────────────────────────
const BRAND = {
  rose: [228, 36, 72] as [number, number, number],
  roseLight: [254, 226, 226] as [number, number, number],
  roseDark: [159, 18, 57] as [number, number, number],
  teal: [20, 184, 166] as [number, number, number],
  dark: [30, 30, 35] as [number, number, number],
  gray: [107, 114, 128] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
};

// ─── Page Constants (A4) ──────────────────────────────────────────────────
const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN_L = 18;
const MARGIN_R = 18;
const CONTENT_W = PAGE_W - MARGIN_L - MARGIN_R; // 174mm
const FOOTER_H = 20;
const SAFE_BOTTOM = PAGE_H - FOOTER_H; // 277mm

// ─── Types ─────────────────────────────────────────────────────────────────
export interface ReferralPdfData {
  consultationNo: string;
  consultationDate: string;
  patientName: string;
  patientId: string;
  patientDateOfBirth?: string;
  patientBarangay?: string;
  typeOfVisit?: string;
  chiefComplaint?: string;
  gravida?: string;
  para?: string;
  aog?: string;
  lmp?: string;
  bloodPressure?: string;
  heartRate?: string;
  temperature?: string;
  weight?: string;
  height?: string;
  bmi?: string;
  respiratoryRate?: string;
  oxygenSat?: string;
  painScale?: string;
  fetalHeartRate?: string;
  fundalHeight?: string;
  allergies?: string;
  medications?: string;
  riskLevel?: string;
  preventionLevel?: string;
  healthHistory?: {
    pastMedicalHistory?: string;
    previousSurgery?: string;
    historyOfTrauma?: string;
    historyOfBloodTransfusion?: string;
    familyHistoryPaternal?: string;
    familyHistoryMaternal?: string;
    smokingHistory?: string;
    alcoholIntake?: string;
    drugUse?: string;
    dietaryPattern?: string;
    physicalActivity?: string;
    sleepPattern?: string;
    allergies?: string;
    currentMedications?: string;
    immunizationStatus?: string;
    mentalHealthHistory?: string;
  };
  healthHistoryRefCode?: string;
  physicalExam?: string;
  labResults?: string;
  notes?: string;
  icd10Diagnosis?: string;
  nandaDiagnosis?: string;
  nandaCode?: string;
  nandaRelatedTo?: string;
  icd10AdditionalNotes?: string;
  aiRationale?: string;
  aiRiskIndicators?: string[];
  aiNursingConsiderations?: string[];
  aiPriorityIntervention?: string;
  aiFollowUpSchedule?: string;
  aiReferralNeeded?: boolean;
  aiReferralReason?: string;
  interventions: Array<{ name: string; description?: string; code?: string }>;
  interventionEvals?: Array<{
    nicCode: string;
    status: string;
    nocOutcome: string;
    nocOutcomeCode: string;
    notes: string;
  }>;
  evaluationNotes?: string;
  referralPriority?: string;
  referralFacility?: string;
  referralType?: string;
}

// ─── Low-level Helpers ─────────────────────────────────────────────────────
function setFont(doc: jsPDF, size: number, style: 'normal' | 'bold' | 'italic' = 'normal') {
  doc.setFont('helvetica', style);
  doc.setFontSize(size);
}

/** Ensure at least `needed` mm of space; add new page if not. */
function ensureSpace(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > SAFE_BOTTOM) {
    doc.addPage();
    drawPageFooter(doc);
    return 25;
  }
  return y;
}

/** Draw footer on the current page. */
function drawPageFooter(doc: jsPDF) {
  const pageNum = doc.getNumberOfPages();
  doc.setDrawColor(...BRAND.rose);
  doc.setLineWidth(0.7);
  doc.line(MARGIN_L, SAFE_BOTTOM + 2, PAGE_W - MARGIN_R, SAFE_BOTTOM + 2);

  setFont(doc, 6.5, 'normal');
  doc.setTextColor(...BRAND.gray);
  doc.text('MOMternal — Maternal Health Nursing Assessment System', MARGIN_L, SAFE_BOTTOM + 7);
  doc.text(`Page ${pageNum}`, PAGE_W - MARGIN_R, SAFE_BOTTOM + 7, { align: 'right' });

  setFont(doc, 5, 'italic');
  doc.setTextColor(170, 170, 180);
  doc.text(
    'This document is auto-generated by MOMternal for healthcare referral purposes only. Confidential.',
    MARGIN_L,
    SAFE_BOTTOM + 12,
  );
}

// ─── Composite Drawing Helpers ─────────────────────────────────────────────

/** Section title with accent underline. Returns y AFTER the section title. */
function drawSectionTitle(
  doc: jsPDF,
  y: number,
  title: string,
  color: [number, number, number] = BRAND.rose,
): number {
  y = ensureSpace(doc, y, 16);
  setFont(doc, 10, 'bold');
  doc.setTextColor(...color);
  const upper = title.toUpperCase();
  doc.text(upper, MARGIN_L, y);
  y += 2;
  doc.setDrawColor(...color);
  doc.setLineWidth(0.5);
  doc.line(MARGIN_L, y, MARGIN_L + doc.getTextWidth(upper), y);
  y += 5;
  return y;
}

/** Sub-section header. Returns y AFTER the sub-header. */
function drawSubTitle(doc: jsPDF, y: number, title: string): number {
  y = ensureSpace(doc, y, 12);
  setFont(doc, 8.5, 'bold');
  doc.setTextColor(...BRAND.dark);
  doc.text(title, MARGIN_L + 5, y);
  y += 6;
  return y;
}

/** Single label: value row. Returns y AFTER the row (or unchanged if empty). */
function drawField(doc: jsPDF, y: number, label: string, value: string): number {
  if (!value || value.trim() === '' || value.trim() === 'N/A') return y;
  y = ensureSpace(doc, y, 8);
  setFont(doc, 8, 'normal');
  doc.setTextColor(...BRAND.gray);
  const lblText = `${label}: `;
  const lblW = doc.getTextWidth(lblText);
  doc.text(lblText, MARGIN_L, y);
  doc.setTextColor(...BRAND.dark);
  const maxW = CONTENT_W - lblW;
  const lines = doc.splitTextToSize(value, maxW);
  doc.text(lines, MARGIN_L + lblW, y);
  y += lines.length * 4.5 + 1.5; // 4.5mm per line + gap
  return y;
}

/**
 * Two-column label-value grid.
 * Each pair goes in its own row. Returns y AFTER the grid.
 */
function drawFieldGrid(
  doc: jsPDF,
  y: number,
  pairs: Array<{ label: string; value: string }>,
  cols = 2,
): number {
  const items = pairs.filter(
    (p) => p.value && p.value.trim() !== '' && p.value.trim() !== 'N/A',
  );
  if (items.length === 0) return y;

  const colW = CONTENT_W / cols;

  items.forEach((item, idx) => {
    const row = Math.floor(idx / cols);
    const col = idx % cols;
    if (col === 0) {
      y = ensureSpace(doc, y, 8);
      if (row > 0) y += 2; // gap between rows
    }
    const x = MARGIN_L + col * colW;

    setFont(doc, 8, 'bold');
    doc.setTextColor(...BRAND.gray);
    const lblText = `${item.label}: `;
    const lblW = doc.getTextWidth(lblText);
    doc.text(lblText, x, y);

    setFont(doc, 8, 'normal');
    doc.setTextColor(...BRAND.dark);
    const valMaxW = colW - lblW - 3;
    const valLines = doc.splitTextToSize(item.value, Math.max(valMaxW, 10));

    // Check if multi-line values in first column would overlap with second column
    if (valLines.length <= 1) {
      doc.text(item.value, x + lblW, y);
    } else {
      // Multi-line: render below the label in full width
      doc.text(valLines, x + lblW, y);
    }
  });

  y += 6; // bottom gap
  return y;
}

/** Colored risk badge. Returns y AFTER the badge. */
function drawBadge(doc: jsPDF, y: number, label: string, bgColor: [number, number, number]): number {
  y = ensureSpace(doc, y, 10);
  setFont(doc, 8, 'bold');
  doc.setTextColor(...bgColor);
  const w = doc.getTextWidth(label) + 14;
  doc.setFillColor(...bgColor);
  doc.roundedRect(MARGIN_L, y - 3.5, w, 7, 1.5, 1.5, 'F');
  doc.setTextColor(...BRAND.white);
  doc.text(label, MARGIN_L + 7, y);
  return y + 8;
}

/** Wrapped text box with background and title. Returns y AFTER the box. */
function drawInfoBox(
  doc: jsPDF,
  y: number,
  title: string,
  body: string,
  bgColor: [number, number, number],
  textColor: [number, number, number],
  titleColor: [number, number, number],
  innerPad = 4,
): number {
  setFont(doc, 7.5, 'normal');
  const bodyLines = doc.splitTextToSize(body, CONTENT_W - innerPad * 2 - 8);
  const boxH = 6 + bodyLines.length * 3.8 + innerPad * 2;

  y = ensureSpace(doc, y, boxH + 2);
  doc.setFillColor(...bgColor);
  doc.roundedRect(MARGIN_L, y, CONTENT_W, boxH, 2, 2, 'F');

  let cy = y + innerPad + 2;
  setFont(doc, 8, 'bold');
  doc.setTextColor(...titleColor);
  doc.text(title, MARGIN_L + innerPad + 2, cy);
  cy += 4.5;

  setFont(doc, 7.5, 'normal');
  doc.setTextColor(...textColor);
  doc.text(bodyLines, MARGIN_L + innerPad + 2, cy);

  return y + boxH + 4;
}

/** Bullet list. Returns y AFTER the list. */
function drawBulletList(doc: jsPDF, y: number, title: string, items: string[]): number {
  if (items.length === 0) return y;
  y = ensureSpace(doc, y, 10);
  setFont(doc, 8, 'bold');
  doc.setTextColor(...BRAND.dark);
  doc.text(title, MARGIN_L, y);
  y += 5;

  items.forEach((item) => {
    y = ensureSpace(doc, y, 6);
    setFont(doc, 7.5, 'normal');
    doc.setTextColor(...BRAND.gray);
    doc.text(`•  ${item}`, MARGIN_L + 5, y);
    y += 4;
  });
  y += 2;
  return y;
}

// ─── Content Checks ────────────────────────────────────────────────────────
function hasAny(...values: (string | undefined | null)[]): boolean {
  return values.some((v) => v && v.trim() !== '');
}

function hasHealthHistory(hh: ReferralPdfData['healthHistory']): boolean {
  if (!hh) return false;
  return hasAny(
    hh.pastMedicalHistory, hh.previousSurgery, hh.historyOfTrauma,
    hh.historyOfBloodTransfusion, hh.familyHistoryPaternal, hh.familyHistoryMaternal,
    hh.smokingHistory, hh.alcoholIntake, hh.drugUse, hh.dietaryPattern,
    hh.physicalActivity, hh.sleepPattern, hh.allergies, hh.currentMedications,
    hh.immunizationStatus, hh.mentalHealthHistory,
  );
}

// ─── Main PDF Generator ────────────────────────────────────────────────────
export async function generateReferralPdf(data: ReferralPdfData): Promise<Blob> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  let y = 0;

  // ═══════════════════════════════════════════════════════════════════════════
  //  HEADER — Branded Banner with Logo
  // ═══════════════════════════════════════════════════════════════════════════
  const headerH = 44;
  doc.setFillColor(...BRAND.rose);
  doc.rect(0, 0, PAGE_W, headerH, 'F');
  // accent line at bottom
  doc.setFillColor(...BRAND.roseDark);
  doc.rect(0, headerH - 2, PAGE_W, 2, 'F');

  // ── Logo (left) ──
  let logoDataUri = '';
  try {
    const resp = await fetch('/momternal_logo.png');
    if (resp.ok) {
      const blob = await resp.blob();
      logoDataUri = await new Promise<string>((resolve) => {
        const r = new FileReader();
        r.onloadend = () => resolve(r.result as string);
        r.readAsDataURL(blob);
      });
    }
  } catch { /* no logo fallback */ }

  if (logoDataUri) {
    const logoW = 55;
    const logoH = 15.8;
    const logoX = MARGIN_L;
    const logoY = 8;
    doc.addImage(logoDataUri, 'PNG', logoX, logoY, logoW, logoH);
  }

  // ── Right-side metadata ──
  setFont(doc, 7.5, 'normal');
  doc.setTextColor(254, 205, 211);
  doc.text(`Consultation No: ${data.consultationNo}`, PAGE_W - MARGIN_R, 14, { align: 'right' });
  doc.text(
    `Date: ${data.consultationDate ? new Date(data.consultationDate).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }) : 'N/A'}`,
    PAGE_W - MARGIN_R,
    20,
    { align: 'right' },
  );

  // Priority badge (right side)
  if (data.referralPriority && data.referralPriority !== 'none') {
    const prioLabel =
      data.referralPriority === 'urgent'
        ? 'URGENT'
        : data.referralPriority === 'same_day'
          ? 'SAME DAY'
          : 'NON-URGENT';
    setFont(doc, 7, 'bold');
    const bw = doc.getTextWidth(prioLabel) + 10;
    const bx = PAGE_W - MARGIN_R - bw;
    doc.setFillColor(255, 255, 255);
    doc.roundedRect(bx, 26, bw, 7, 1.5, 1.5, 'F');
    doc.setTextColor(...BRAND.rose);
    doc.text(prioLabel, bx + bw / 2, 30, { align: 'center' });
  }

  // ── Bottom text (left-aligned, inside banner) ──
  setFont(doc, 8.5, 'normal');
  doc.setTextColor(254, 205, 211);
  doc.text('Maternal Health Nursing Assessment System', MARGIN_L, headerH - 11);
  setFont(doc, 8, 'bold');
  doc.setTextColor(...BRAND.white);
  doc.text('REFERRAL DOCUMENT', MARGIN_L, headerH - 5);

  y = headerH + 6; // 50

  // ═══════════════════════════════════════════════════════════════════════════
  //  1. PATIENT INFORMATION
  // ═══════════════════════════════════════════════════════════════════════════
  y = drawSectionTitle(doc, y, 'Patient Information');

  setFont(doc, 12, 'bold');
  doc.setTextColor(...BRAND.dark);
  doc.text(data.patientName || 'N/A', MARGIN_L, y);
  y += 7;

  y = drawFieldGrid(doc, y, [
    { label: 'Patient ID', value: data.patientId || 'N/A' },
    { label: 'Date of Birth', value: data.patientDateOfBirth || '' },
    { label: 'Barangay', value: data.patientBarangay || '' },
    { label: 'Type of Visit', value: data.typeOfVisit || '' },
  ], 2);

  // OB History
  const obPairs: Array<{ label: string; value: string }> = [];
  if (data.gravida) obPairs.push({ label: 'Gravida', value: data.gravida });
  if (data.para) obPairs.push({ label: 'Para', value: data.para });
  if (data.lmp) obPairs.push({ label: 'LMP', value: data.lmp });
  if (data.aog) obPairs.push({ label: 'AOG', value: data.aog });
  if (obPairs.length > 0) {
    y = drawFieldGrid(doc, y, obPairs, Math.min(obPairs.length, 4));
  }

  // Risk badge
  if (data.riskLevel && data.riskLevel.trim()) {
    const riskVal = data.riskLevel.toUpperCase();
    const riskColors: Record<string, [number, number, number]> = {
      HIGH: [220, 38, 38],
      MODERATE: [245, 158, 11],
      LOW: [34, 197, 94],
    };
    y = drawBadge(doc, y, `Risk Level: ${riskVal}`, riskColors[riskVal] ?? BRAND.gray);
    if (data.preventionLevel) {
      const pl = `(Prevention: ${data.preventionLevel.charAt(0).toUpperCase() + data.preventionLevel.slice(1)})`;
      setFont(doc, 7.5, 'italic');
      doc.setTextColor(...BRAND.gray);
      doc.text(pl, MARGIN_L + 5, y - 4);
    }
  }

  y += 3;

  // ═══════════════════════════════════════════════════════════════════════════
  //  2. CLINICAL ASSESSMENT
  // ═══════════════════════════════════════════════════════════════════════════
  if (hasAny(data.chiefComplaint, data.bloodPressure, data.temperature, data.allergies, data.medications)) {
    y = drawSectionTitle(doc, y, 'Clinical Assessment');

    y = drawField(doc, y, 'Chief Complaint', data.chiefComplaint || '');

    // Vitals — 2 columns (safer, no overlap)
    const vitals: Array<{ label: string; value: string }> = [];
    if (data.bloodPressure) vitals.push({ label: 'Blood Pressure', value: data.bloodPressure });
    if (data.heartRate) vitals.push({ label: 'Heart Rate', value: `${data.heartRate} bpm` });
    if (data.temperature) vitals.push({ label: 'Temperature', value: `${data.temperature}\u00B0C` });
    if (data.respiratoryRate) vitals.push({ label: 'Respiratory Rate', value: `${data.respiratoryRate} cpm` });
    if (data.oxygenSat) vitals.push({ label: 'O\u2082 Saturation', value: `${data.oxygenSat}%` });
    if (data.painScale) vitals.push({ label: 'Pain Scale', value: `${data.painScale}/10` });
    if (data.fetalHeartRate) vitals.push({ label: 'Fetal Heart Rate', value: data.fetalHeartRate });
    if (data.fundalHeight) vitals.push({ label: 'Fundal Height', value: data.fundalHeight });
    if (data.weight) vitals.push({ label: 'Weight', value: `${data.weight} kg` });
    if (data.height) vitals.push({ label: 'Height', value: `${data.height} cm` });
    if (data.bmi) vitals.push({ label: 'BMI', value: data.bmi });
    if (vitals.length > 0) {
      y = drawFieldGrid(doc, y, vitals, 2);
    }

    y = drawField(doc, y, 'Allergies', data.allergies || '');
    y = drawField(doc, y, 'Current Medications', data.medications || '');
    y += 3;
  }

  // ═══════════════════════════════════════════════════════════════════════════
  //  3. HEALTH HISTORY
  // ═══════════════════════════════════════════════════════════════════════════
  if (hasHealthHistory(data.healthHistory)) {
    y = drawSectionTitle(doc, y, 'Health History', BRAND.teal);
    const hh = data.healthHistory!;

    if (data.healthHistoryRefCode) {
      y = ensureSpace(doc, y, 8);
      setFont(doc, 7, 'italic');
      doc.setTextColor(...BRAND.teal);
      doc.text(`Reference: ${data.healthHistoryRefCode}`, MARGIN_L + 5, y);
      y += 6;
    }

    // Medical & Surgical
    if (hasAny(hh.pastMedicalHistory, hh.previousSurgery, hh.historyOfTrauma, hh.historyOfBloodTransfusion)) {
      y = drawSubTitle(doc, y, 'Medical & Surgical History');
      y = drawField(doc, y, 'Past Medical History', hh.pastMedicalHistory || '');
      y = drawField(doc, y, 'Previous Surgery', hh.previousSurgery || '');
      y = drawField(doc, y, 'History of Trauma', hh.historyOfTrauma || '');
      y = drawField(doc, y, 'Blood Transfusion', hh.historyOfBloodTransfusion || '');
      y += 2;
    }

    // Family
    if (hasAny(hh.familyHistoryPaternal, hh.familyHistoryMaternal)) {
      y = drawSubTitle(doc, y, 'Family History');
      y = drawField(doc, y, 'Paternal Side', hh.familyHistoryPaternal || '');
      y = drawField(doc, y, 'Maternal Side', hh.familyHistoryMaternal || '');
      y += 2;
    }

    // Personal & Social
    if (hasAny(hh.smokingHistory, hh.alcoholIntake, hh.drugUse, hh.dietaryPattern, hh.physicalActivity, hh.sleepPattern)) {
      y = drawSubTitle(doc, y, 'Personal & Social History');
      y = drawFieldGrid(doc, y, [
        { label: 'Smoking', value: hh.smokingHistory || '' },
        { label: 'Alcohol Intake', value: hh.alcoholIntake || '' },
        { label: 'Drug Use', value: hh.drugUse || '' },
        { label: 'Dietary Pattern', value: hh.dietaryPattern || '' },
        { label: 'Physical Activity', value: hh.physicalActivity || '' },
        { label: 'Sleep Pattern', value: hh.sleepPattern || '' },
      ], 2);
    }

    // Additional
    if (hasAny(hh.allergies, hh.currentMedications, hh.immunizationStatus, hh.mentalHealthHistory)) {
      y = drawSubTitle(doc, y, 'Additional Information');
      y = drawField(doc, y, 'Known Allergies', hh.allergies || '');
      y = drawField(doc, y, 'Current Medications', hh.currentMedications || '');
      y = drawField(doc, y, 'Immunization Status', hh.immunizationStatus || '');
      y = drawField(doc, y, 'Mental Health History', hh.mentalHealthHistory || '');
      y += 2;
    }
    y += 3;
  }

  // ═══════════════════════════════════════════════════════════════════════════
  //  4. FINDINGS
  // ═══════════════════════════════════════════════════════════════════════════
  if (hasAny(data.physicalExam, data.labResults, data.notes)) {
    y = drawSectionTitle(doc, y, 'Additional Findings');
    y = drawField(doc, y, 'Physical Examination', data.physicalExam || '');
    y = drawField(doc, y, 'Laboratory Results', data.labResults || '');
    y = drawField(doc, y, 'Additional Notes', data.notes || '');
    y += 3;
  }

  // ═══════════════════════════════════════════════════════════════════════════
  //  5. DIAGNOSIS
  // ═══════════════════════════════════════════════════════════════════════════
  if (hasAny(data.icd10Diagnosis, data.nandaDiagnosis, data.nandaRelatedTo, data.icd10AdditionalNotes)) {
    y = drawSectionTitle(doc, y, 'Diagnosis');

    if (data.nandaDiagnosis) {
      y = drawField(doc, y, 'NANDA-I Nursing Diagnosis', data.nandaDiagnosis);
      if (data.nandaCode) {
        setFont(doc, 7, 'italic');
        doc.setTextColor(...BRAND.gray);
        doc.text(`(NANDA Code: ${data.nandaCode})`, MARGIN_L + 5, y);
        y += 5;
      }
    }
    if (data.nandaRelatedTo) {
      y = drawField(doc, y, 'Related to', data.nandaRelatedTo);
    }
    if (data.icd10Diagnosis) {
      y = drawField(doc, y, 'ICD-10 Diagnosis', data.icd10Diagnosis);
    }
    if (data.icd10AdditionalNotes) {
      y = drawField(doc, y, 'Additional Notes', data.icd10AdditionalNotes);
    }
    y += 3;
  }

  // ═══════════════════════════════════════════════════════════════════════════
  //  6. AI SUMMARY
  // ═══════════════════════════════════════════════════════════════════════════
  const hasAi = hasAny(data.aiRationale, data.aiPriorityIntervention, data.aiFollowUpSchedule, data.aiReferralReason)
    || (data.aiRiskIndicators && data.aiRiskIndicators.length > 0)
    || (data.aiNursingConsiderations && data.aiNursingConsiderations.length > 0);

  if (hasAi) {
    y = drawSectionTitle(doc, y, 'AI-Assisted Summary');

    if (data.aiRationale) {
      y = drawInfoBox(doc, y, 'Rationale', data.aiRationale, BRAND.roseLight, BRAND.roseDark, BRAND.roseDark);
    }

    if (data.aiRiskIndicators && data.aiRiskIndicators.length > 0) {
      y = drawBulletList(doc, y, 'Risk Indicators:', data.aiRiskIndicators);
    }

    if (data.aiPriorityIntervention) {
      y = drawInfoBox(
        doc, y,
        'Priority Intervention',
        data.aiPriorityIntervention,
        [254, 243, 199] as [number, number, number], // amber-100
        [146, 64, 14] as [number, number, number],   // amber-800
        [146, 64, 14] as [number, number, number],
      );
    }

    if (data.aiNursingConsiderations && data.aiNursingConsiderations.length > 0) {
      y = drawBulletList(doc, y, 'Nursing Considerations:', data.aiNursingConsiderations);
    }

    if (data.aiFollowUpSchedule) {
      y = drawField(doc, y, 'Follow-up Schedule', data.aiFollowUpSchedule);
    }
    if (data.aiReferralNeeded && data.aiReferralReason) {
      y = drawField(doc, y, 'AI Referral Reason', data.aiReferralReason);
    }
    y += 3;
  }

  // ═══════════════════════════════════════════════════════════════════════════
  //  7. CARE PLAN
  // ═══════════════════════════════════════════════════════════════════════════
  if (data.interventions.length > 0 || hasAny(data.evaluationNotes)) {
    y = drawSectionTitle(doc, y, 'Nursing Care Plan');

    if (data.interventions.length > 0) {
      setFont(doc, 8.5, 'bold');
      doc.setTextColor(...BRAND.dark);
      doc.text(`Selected Interventions (${data.interventions.length}):`, MARGIN_L, y);
      y += 6;

      data.interventions.forEach((intervention, idx) => {
        y = ensureSpace(doc, y, 10);
        setFont(doc, 8.5, 'bold');
        doc.setTextColor(...BRAND.dark);
        const code = intervention.code ? `[${intervention.code}] ` : '';
        doc.text(`${idx + 1}. ${code}${intervention.name}`, MARGIN_L, y);
        y += 5;

        if (intervention.description) {
          setFont(doc, 8, 'normal');
          doc.setTextColor(...BRAND.gray);
          const descLines = doc.splitTextToSize(intervention.description, CONTENT_W - 10);
          doc.text(descLines, MARGIN_L + 5, y);
          y += descLines.length * 4 + 1;
        }

        // Per-intervention evaluation
        const evalItem = data.interventionEvals?.find(
          (e) => e.nicCode === intervention.code || e.nicCode === String(intervention.code),
        );
        if (evalItem) {
          y += 1;
          const statusColors: Record<string, [number, number, number]> = {
            met: [34, 197, 94],
            partially_met: [245, 158, 11],
            unmet: [220, 38, 38],
          };
          const statusLabel = evalItem.status.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
          const sc = statusColors[evalItem.status] ?? BRAND.gray;
          setFont(doc, 7.5, 'bold');
          doc.setTextColor(...sc);
          doc.text(`Evaluation: ${statusLabel}`, MARGIN_L + 5, y);
          y += 4.5;
          if (evalItem.nocOutcome) {
            setFont(doc, 7.5, 'normal');
            doc.setTextColor(...BRAND.gray);
            const nocLabel = evalItem.nocOutcomeCode ? `NOC [${evalItem.nocOutcomeCode}]: ` : 'NOC Outcome: ';
            doc.text(nocLabel + evalItem.nocOutcome, MARGIN_L + 5, y);
            y += 4.5;
          }
          if (evalItem.notes) {
            setFont(doc, 7.5, 'italic');
            doc.setTextColor(...BRAND.gray);
            const evalNotes = doc.splitTextToSize(evalItem.notes, CONTENT_W - 15);
            doc.text(evalNotes, MARGIN_L + 5, y);
            y += evalNotes.length * 3.5 + 1;
          }
        }
        y += 3;
      });
    }

    if (data.evaluationNotes) {
      y = drawField(doc, y, 'Overall Outcome Summary', data.evaluationNotes);
    }
    y += 3;
  }

  // ═══════════════════════════════════════════════════════════════════════════
  //  8. REFERRAL DETAILS
  // ═══════════════════════════════════════════════════════════════════════════
  y = drawSectionTitle(doc, y, 'Referral Details');
  y = drawField(doc, y, 'Referral Type', data.referralType || 'Refer to Doctor');

  if (data.referralPriority && data.referralPriority !== 'none') {
    const prioLabel =
      data.referralPriority === 'urgent' ? 'Urgent'
        : data.referralPriority === 'same_day' ? 'Same Day'
          : 'Non-urgent';
    y = drawField(doc, y, 'Priority', prioLabel);
  }

  y = drawField(doc, y, 'Referred Facility', data.referralFacility || 'Not specified');
  y += 5;

  // ═══════════════════════════════════════════════════════════════════════════
  //  SIGNATURE AREA
  // ═══════════════════════════════════════════════════════════════════════════
  y = ensureSpace(doc, y, 45);
  doc.setDrawColor(...BRAND.gray);
  doc.setLineWidth(0.3);
  doc.line(MARGIN_L, y, PAGE_W - MARGIN_R, y);
  y += 6;

  setFont(doc, 8, 'bold');
  doc.setTextColor(...BRAND.dark);
  doc.text('Prepared by:', MARGIN_L, y);
  y += 12;

  // Nurse signature line
  doc.line(MARGIN_L, y, 85, y);
  // Date line
  doc.line(110, y, PAGE_W - MARGIN_R, y);

  setFont(doc, 7, 'normal');
  doc.setTextColor(...BRAND.gray);
  doc.text('Nurse Signature over Printed Name', MARGIN_L, y + 4);
  doc.text('Date & Time', 110, y + 4);
  y += 15;

  // Physician signature line
  doc.line(MARGIN_L, y, 85, y);
  doc.line(110, y, PAGE_W - MARGIN_R, y);

  doc.text('Receiving Physician Signature over Printed Name', MARGIN_L, y + 4);
  doc.text('Date & Time', 110, y + 4);

  // ═══════════════════════════════════════════════════════════════════════════
  //  FOOTERS on every page
  // ═══════════════════════════════════════════════════════════════════════════
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    drawPageFooter(doc);
  }

  return doc.output('blob');
}
