import jsPDF from 'jspdf';

// ─── Color Palette (MOMternal Brand) ──────────────────────────────────────
const BRAND = {
  rose: [228, 36, 72] as [number, number, number],       // #E42448
  roseLight: [254, 226, 226] as [number, number, number], // #FEE2E2
  roseDark: [159, 18, 57] as [number, number, number],   // #9F1239
  dark: [30, 30, 35] as [number, number, number],         // near-black
  gray: [107, 114, 128] as [number, number, number],      // #6B7280
  grayLight: [243, 244, 246] as [number, number, number], // #F3F4F6
  white: [255, 255, 255] as [number, number, number],
  black: [0, 0, 0] as [number, number, number],
};

// ─── Types ─────────────────────────────────────────────────────────────────
export interface ReferralPdfData {
  consultationNo: string;
  consultationDate: string;
  patientName: string;
  patientId: string;
  patientDateOfBirth?: string;
  patientBarangay?: string;
  typeOfVisit?: string;
  chiefComplaint?: string;
  gravida?: string;
  para?: string;
  aog?: string;
  riskLevel?: string;
  preventionLevel?: string;
  bloodPressure?: string;
  heartRate?: string;
  temperature?: string;
  weight?: string;
  respiratoryRate?: string;
  oxygenSat?: string;
  fetalHeartRate?: string;
  fundalHeight?: string;
  bmi?: string;
  height?: string;
  allergies?: string;
  medications?: string;
  physicalExam?: string;
  labResults?: string;
  notes?: string;
  icd10Diagnosis?: string;
  nandaDiagnosis?: string;
  nandaCode?: string;
  referralPriority?: string;
  referralFacility?: string;
  referralType?: string;
  interventions: Array<{ name: string; description?: string; code?: string }>;
  interventionEvals?: Array<{
    nicCode: string;
    status: string;
    nocOutcome: string;
    nocOutcomeCode: string;
    notes: string;
  }>;
  evaluationNotes?: string;
  aiRationale?: string;
}

// ─── Helpers ───────────────────────────────────────────────────────────────
function rgb(color: [number, number, number]): string {
  return color.join(',');
}

function setFont(doc: jsPDF, size: number, style: 'normal' | 'bold' | 'italic' = 'normal') {
  doc.setFont('helvetica', style);
  doc.setFontSize(size);
}

function drawHr(doc: jsPDF, y: number, color: [number, number, number] = BRAND.grayLight, width?: number) {
  const x = 15;
  const w = width ?? (doc.internal.pageSize.getWidth() - 30);
  doc.setDrawColor(...color);
  doc.setLineWidth(0.3);
  doc.line(x, y, x + w, y);
  return y + 4;
}

function checkPageBreak(doc: jsPDF, y: number, needed: number): number {
  const pageH = doc.internal.pageSize.getHeight();
  if (y + needed > pageH - 25) {
    doc.addPage();
    drawPageFooter(doc, 0);
    return 20;
  }
  return y;
}

function drawPageFooter(doc: jsPDF, _unused: number) {
  const pageH = doc.internal.pageSize.getHeight();
  const pageW = doc.internal.pageSize.getWidth();
  const pageNum = doc.getNumberOfPages();

  // Footer line
  doc.setDrawColor(...BRAND.rose);
  doc.setLineWidth(0.8);
  doc.line(15, pageH - 18, pageW - 15, pageH - 18);

  // Footer text
  setFont(doc, 7, 'normal');
  doc.setTextColor(...BRAND.gray);
  doc.text('MOMternal — Maternal Health Nursing Assessment System', 15, pageH - 12);
  doc.text(`Page ${pageNum}`, pageW - 15, pageH - 12, { align: 'right' });

  // Disclaimer
  setFont(doc, 5.5, 'italic');
  doc.setTextColor(180, 180, 190);
  doc.text(
    'This document is auto-generated by MOMternal for healthcare referral purposes only. Confidential.',
    15,
    pageH - 7
  );
}

function drawSectionHeader(doc: jsPDF, y: number, title: string): number {
  y = checkPageBreak(doc, y, 20);
  setFont(doc, 10, 'bold');
  doc.setTextColor(...BRAND.rose);
  doc.text(title.toUpperCase(), 15, y);
  y += 1.5;
  // Underline
  doc.setDrawColor(...BRAND.rose);
  doc.setLineWidth(0.6);
  doc.line(15, y, 15 + doc.getTextWidth(title.toUpperCase()), y);
  y += 5;
  return y;
}

function drawDataRow(doc: jsPDF, y: number, label: string, value: string, pageWidth: number): number {
  if (!value || value.trim() === '' || value.trim() === 'N/A') return y;
  y = checkPageBreak(doc, y, 8);
  setFont(doc, 8.5, 'normal');
  doc.setTextColor(...BRAND.gray);
  const labelW = doc.getTextWidth(label + ': ');
  doc.text(label + ':', 20, y);
  doc.setTextColor(...BRAND.dark);
  // Wrap long values
  const maxValW = pageWidth - 20 - labelW - 15;
  const lines = doc.splitTextToSize(value, maxValW);
  doc.text(lines, 20 + labelW, y);
  return y + (lines.length * 4.5);
}

function drawLabelValueGrid(
  doc: jsPDF,
  y: number,
  pairs: Array<{ label: string; value: string }>,
  pageWidth: number,
  columns = 2
): number {
  const filtered = pairs.filter((p) => p.value && p.value.trim() !== '' && p.value.trim() !== 'N/A');
  if (filtered.length === 0) return y;

  const colWidth = (pageWidth - 40) / columns;
  y = checkPageBreak(doc, y, 10);

  filtered.forEach((pair, idx) => {
    const col = idx % columns;
    const row = Math.floor(idx / columns);
    if (col === 0 && row > 0) {
      y += 6;
      y = checkPageBreak(doc, y, 10);
    }
    const x = 20 + col * colWidth;

    setFont(doc, 8, 'bold');
    doc.setTextColor(...BRAND.gray);
    doc.text(pair.label + ':', x, y);
    setFont(doc, 8, 'normal');
    doc.setTextColor(...BRAND.dark);
    doc.text(pair.value, x + doc.getTextWidth(pair.label + ': '), y);
  });

  return y + 6;
}

// ─── Main PDF Generator ────────────────────────────────────────────────────
export async function generateReferralPdf(data: ReferralPdfData): Promise<Blob> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  let y = 0;

  // ════════════════════════════════════════════════════════════════════════
  // HEADER — Branded Rose Banner
  // ════════════════════════════════════════════════════════════════════════
  // Rose banner background
  doc.setFillColor(...BRAND.rose);
  doc.rect(0, 0, pageW, 42, 'F');

  // Decorative lighter strip at bottom of banner
  doc.setFillColor(...BRAND.roseDark);
  doc.rect(0, 40, pageW, 2, 'F');

  // Logo placeholder icon (heart + stethoscope circle)
  doc.setFillColor(...BRAND.white);
  doc.setDrawColor(...BRAND.white);
  doc.setLineWidth(0.8);
  doc.circle(18, 21, 8, 'FD');

  // Draw a simple heart shape in the circle
  setFont(doc, 14, 'bold');
  doc.setTextColor(...BRAND.rose);
  doc.text('♥', 18, 23.5, { align: 'center' });

  // Title text
  setFont(doc, 22, 'bold');
  doc.setTextColor(...BRAND.white);
  doc.text('MOMTERNAL', 30, 17);

  setFont(doc, 9, 'normal');
  doc.setTextColor(254, 205, 211); // rose-200
  doc.text('Maternal Health Nursing Assessment System', 30, 24);

  // Document type badge
  setFont(doc, 8, 'bold');
  doc.setTextColor(...BRAND.white);
  doc.text('REFERRAL DOCUMENT', 30, 32);

  // Right side: consultation info in banner
  setFont(doc, 7.5, 'normal');
  doc.setTextColor(254, 205, 211);
  doc.text(`Consultation No: ${data.consultationNo}`, pageW - 15, 14, { align: 'right' });
  doc.text(
    `Date: ${data.consultationDate ? new Date(data.consultationDate).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }) : 'N/A'}`,
    pageW - 15,
    20,
    { align: 'right' }
  );

  // Priority badge (if set)
  if (data.referralPriority && data.referralPriority !== 'none') {
    const priorityLabel =
      data.referralPriority === 'urgent'
        ? '⚠ URGENT'
        : data.referralPriority === 'same_day'
          ? '◉ SAME DAY'
          : '○ NON-URGENT';
    doc.setFillColor(255, 255, 255);
    const badgeW = doc.getTextWidth(priorityLabel) + 8;
    doc.roundedRect(pageW - 15 - badgeW, 25, badgeW, 7, 1.5, 1.5, 'F');
    setFont(doc, 7, 'bold');
    doc.setTextColor(...BRAND.rose);
    doc.text(priorityLabel, pageW - 15 - badgeW / 2, 29.5, { align: 'center' });
  }

  // White card area starts
  y = 48;

  // ════════════════════════════════════════════════════════════════════════
  // SECTION 1: PATIENT INFORMATION
  // ════════════════════════════════════════════════════════════════════════
  y = drawSectionHeader(doc, y, 'Patient Information');

  // Patient name (large, prominent)
  setFont(doc, 12, 'bold');
  doc.setTextColor(...BRAND.dark);
  doc.text(data.patientName || 'N/A', 20, y);
  y += 6;

  // Grid info
  y = drawLabelValueGrid(
    doc,
    y,
    [
      { label: 'Patient ID', value: data.patientId || 'N/A' },
      { label: 'Date of Birth', value: data.patientDateOfBirth || '' },
      { label: 'Barangay', value: data.patientBarangay || '' },
      { label: 'Type of Visit', value: data.typeOfVisit || '' },
    ],
    pageW,
    2
  );

  // OB History row
  const obFields: Array<{ label: string; value: string }> = [];
  if (data.gravida) obFields.push({ label: 'Gravida', value: data.gravida });
  if (data.para) obFields.push({ label: 'Para', value: data.para });
  if (data.aog) obFields.push({ label: 'AOG', value: data.aog });
  if (obFields.length > 0) {
    y = drawLabelValueGrid(doc, y, obFields, pageW, obFields.length);
  }

  // Risk level badge
  if (data.riskLevel && data.riskLevel.trim()) {
    y = checkPageBreak(doc, y, 14);
    const riskVal = data.riskLevel.toUpperCase();
    const riskColors: Record<string, [number, number, number]> = {
      HIGH: [220, 38, 38],
      MODERATE: [245, 158, 11],
      LOW: [34, 197, 94],
    };
    const rc = riskColors[riskVal] ?? BRAND.gray;

    // Risk badge background
    const badgeLabel = `Risk Level: ${riskVal}`;
    const bw = doc.getTextWidth(badgeLabel) + 14;
    doc.setFillColor(...rc);
    doc.roundedRect(20, y - 3.5, bw, 7, 2, 2, 'F');
    setFont(doc, 8.5, 'bold');
    doc.setTextColor(...BRAND.white);
    doc.text(badgeLabel, 20 + 7, y + 0.5);

    if (data.preventionLevel) {
      const pl = `(Prevention: ${data.preventionLevel.charAt(0).toUpperCase() + data.preventionLevel.slice(1)})`;
      setFont(doc, 7.5, 'italic');
      doc.setTextColor(...BRAND.gray);
      doc.text(pl, 20 + bw + 5, y + 0.5);
    }
    y += 8;
  }

  y += 2;

  // ════════════════════════════════════════════════════════════════════════
  // SECTION 2: CLINICAL ASSESSMENT
  // ════════════════════════════════════════════════════════════════════════
  if (data.chiefComplaint || data.bloodPressure || data.temperature) {
    y = drawSectionHeader(doc, y, 'Clinical Assessment');

    if (data.chiefComplaint) {
      y = drawDataRow(doc, y, 'Chief Complaint', data.chiefComplaint, pageW);
      y += 1;
    }

    // Vitals grid
    const vitalsPairs: Array<{ label: string; value: string }> = [];
    if (data.bloodPressure) vitalsPairs.push({ label: 'Blood Pressure', value: data.bloodPressure });
    if (data.heartRate) vitalsPairs.push({ label: 'Heart Rate', value: `${data.heartRate} bpm` });
    if (data.temperature) vitalsPairs.push({ label: 'Temperature', value: `${data.temperature}°C` });
    if (data.weight) vitalsPairs.push({ label: 'Weight', value: `${data.weight} kg` });
    if (data.height) vitalsPairs.push({ label: 'Height', value: `${data.height} cm` });
    if (data.bmi) vitalsPairs.push({ label: 'BMI', value: data.bmi });
    if (data.respiratoryRate) vitalsPairs.push({ label: 'Respiratory Rate', value: `${data.respiratoryRate} cpm` });
    if (data.oxygenSat) vitalsPairs.push({ label: 'O2 Saturation', value: `${data.oxygenSat}%` });
    if (data.fetalHeartRate) vitalsPairs.push({ label: 'Fetal Heart Rate', value: data.fetalHeartRate });
    if (data.fundalHeight) vitalsPairs.push({ label: 'Fundal Height', value: data.fundalHeight });

    if (vitalsPairs.length > 0) {
      y = drawLabelValueGrid(doc, y, vitalsPairs, pageW, 2);
    }

    y = drawDataRow(doc, y, 'Allergies', data.allergies || '', pageW);
    y = drawDataRow(doc, y, 'Current Medications', data.medications || '', pageW);
    y += 2;
  }

  // ════════════════════════════════════════════════════════════════════════
  // SECTION 3: FINDINGS
  // ════════════════════════════════════════════════════════════════════════
  if (data.physicalExam || data.labResults || data.notes) {
    y = drawSectionHeader(doc, y, 'Additional Findings');
    y = drawDataRow(doc, y, 'Physical Examination', data.physicalExam || '', pageW);
    y = drawDataRow(doc, y, 'Laboratory Results', data.labResults || '', pageW);
    y = drawDataRow(doc, y, 'Notes', data.notes || '', pageW);
    y += 2;
  }

  // ════════════════════════════════════════════════════════════════════════
  // SECTION 4: DIAGNOSIS
  // ════════════════════════════════════════════════════════════════════════
  if (data.icd10Diagnosis || data.nandaDiagnosis) {
    y = drawSectionHeader(doc, y, 'Diagnosis');
    y = drawDataRow(doc, y, 'ICD-10 Diagnosis', data.icd10Diagnosis || '', pageW);
    y = drawDataRow(doc, y, 'NANDA-I Nursing Diagnosis', data.nandaDiagnosis || '', pageW);
    if (data.nandaCode) {
      setFont(doc, 7.5, 'italic');
      doc.setTextColor(...BRAND.gray);
      doc.text(`(NANDA Code: ${data.nandaCode})`, 20, y);
      y += 5;
    }
    y += 2;
  }

  // ════════════════════════════════════════════════════════════════════════
  // SECTION 5: NURSING INTERVENTIONS (NIC)
  // ════════════════════════════════════════════════════════════════════════
  if (data.interventions.length > 0) {
    y = drawSectionHeader(doc, y, 'Nursing Interventions (NIC)');

    data.interventions.forEach((intervention, idx) => {
      y = checkPageBreak(doc, y, 12);
      setFont(doc, 8.5, 'bold');
      doc.setTextColor(...BRAND.dark);
      const code = intervention.code ? `[${intervention.code}] ` : '';
      doc.text(`${idx + 1}. ${code}${intervention.name}`, 20, y);
      y += 4;
      if (intervention.description) {
        setFont(doc, 8, 'normal');
        doc.setTextColor(...BRAND.gray);
        const descLines = doc.splitTextToSize(intervention.description, pageW - 40);
        doc.text(descLines, 25, y);
        y += descLines.length * 4;
      }

      // Check if there's an evaluation for this intervention
      const evalItem = data.interventionEvals?.find(
        (e) => e.nicCode === intervention.code || e.nicCode === String(intervention.code)
      );
      if (evalItem) {
        y += 1;
        const statusColors: Record<string, [number, number, number]> = {
          Met: [34, 197, 94],
          'Partially Met': [245, 158, 11],
          Unmet: [220, 38, 38],
        };
        const sc = statusColors[evalItem.status] ?? BRAND.gray;
        setFont(doc, 7.5, 'bold');
        doc.setTextColor(...sc);
        doc.text(`Evaluation: ${evalItem.status}`, 28, y);
        y += 4;
        if (evalItem.nocOutcome) {
          setFont(doc, 7.5, 'normal');
          doc.setTextColor(...BRAND.gray);
          const nocLabel = evalItem.nocOutcomeCode ? `NOC [${evalItem.nocOutcomeCode}]: ` : 'NOC Outcome: ';
          doc.text(nocLabel + evalItem.nocOutcome, 28, y);
          y += 4;
        }
        if (evalItem.notes) {
          setFont(doc, 7.5, 'italic');
          doc.setTextColor(...BRAND.gray);
          const evalNotes = doc.splitTextToSize(evalItem.notes, pageW - 50);
          doc.text(evalNotes, 28, y);
          y += evalNotes.length * 3.5;
        }
      }
      y += 2;
    });

    // AI Rationale
    if (data.aiRationale) {
      y = checkPageBreak(doc, y, 15);
      y += 1;
      doc.setFillColor(...BRAND.roseLight);
      const rationaleLines = doc.splitTextToSize(`AI Rationale: ${data.aiRationale}`, pageW - 44);
      const boxH = rationaleLines.length * 4 + 6;
      doc.roundedRect(18, y - 4, pageW - 36, boxH, 2, 2, 'F');
      setFont(doc, 7.5, 'italic');
      doc.setTextColor(...BRAND.roseDark);
      doc.text(rationaleLines, 22, y);
      y += boxH + 3;
    }
    y += 2;
  }

  // ════════════════════════════════════════════════════════════════════════
  // SECTION 6: REFERRAL DETAILS
  // ════════════════════════════════════════════════════════════════════════
  y = drawSectionHeader(doc, y, 'Referral Details');

  y = drawDataRow(doc, y, 'Referral Type', data.referralType || 'Refer to Doctor', pageW);
  y = drawDataRow(doc, y, 'Priority', data.referralPriority || 'Not specified', pageW);
  y = drawDataRow(doc, y, 'Referred Facility', data.referralFacility || '', pageW);

  if (data.evaluationNotes) {
    y += 1;
    y = drawDataRow(doc, y, 'Evaluation Notes', data.evaluationNotes, pageW);
  }

  y += 4;

  // ════════════════════════════════════════════════════════════════════════
  // SECTION 7: SIGNATURE AREA
  // ════════════════════════════════════════════════════════════════════════
  y = checkPageBreak(doc, y, 40);
  y = drawHr(doc, y, BRAND.gray);
  y += 4;

  setFont(doc, 8, 'bold');
  doc.setTextColor(...BRAND.dark);
  doc.text('Prepared by:', 20, y);
  y += 12;

  // Signature lines
  doc.setDrawColor(...BRAND.gray);
  doc.setLineWidth(0.3);
  doc.line(20, y, 80, y);
  doc.line(110, y, pageW - 15, y);

  setFont(doc, 7, 'normal');
  doc.setTextColor(...BRAND.gray);
  doc.text('Nurse Signature', 20, y + 4);
  doc.text('Date & Time', 110, y + 4);
  y += 15;

  // Receiving facility line
  doc.line(20, y, 80, y);
  doc.text('Receiving Physician Signature', 20, y + 4);
  doc.line(110, y, pageW - 15, y);
  doc.text('Date & Time', 110, y + 4);

  // ════════════════════════════════════════════════════════════════════════
  // Draw footers on all pages
  // ════════════════════════════════════════════════════════════════════════
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    drawPageFooter(doc, 0);
  }

  return doc.output('blob');
}
