/**
 * MOMternal Offline Consultation Store
 *
 * Manages consultation data locally when the user creates or edits a consultation
 * while offline. Consultations are stored in localStorage keyed by a temp ID
 * (format: `offline-{timestamp}-{random}`).
 *
 * Features:
 * - Create / read / update / delete offline consultations
 * - Temp-to-real ID mapping after successful sync
 * - Lookup by real ID for post-sync navigation
 * - Cleanup of synced records
 * - All localStorage access wrapped in try-catch for resilience
 */

// ── Types ────────────────────────────────────────────────────────────────

export interface OfflineConsultation {
  tempId: string;              // The temp ID generated by offlineFetch
  patientId: string;           // The real patient DB ID
  patientName?: string;        // Patient name for display
  patientPatientId?: string;   // Patient's patient_id (display ID like "MOM-0001")
  nurseId: string;             // The nurse's DB ID
  nurseName?: string;          // Nurse's name for display
  createdAt: string;           // ISO timestamp
  updatedAt: string;           // ISO timestamp
  consultationNo: string;      // "OFFLINE-TEMP" placeholder
  consultationDate: string;    // ISO date string
  stepCompleted: number;       // Current wizard step
  status: string;              // "in_progress"
  realId?: string;             // Set after successful sync — the real DB consultation ID

  // All the consultation form fields (same as ConsultationData interface):
  typeOfVisit?: string | null;
  chiefComplaint?: string | null;
  subjectiveSymptoms?: string | null;
  objectiveVitals?: string | null;
  fetalHeartRate?: string | null;
  fundalHeight?: string | null;
  allergies?: string | null;
  medications?: string | null;
  physicalExam?: string | null;
  labResults?: string | null;
  notes?: string | null;
  icd10Diagnosis?: string | null;
  nandaDiagnosis?: string | null;
  nandaCode?: string | null;
  nandaName?: string | null;
  nandaRelatedTo?: string | null;
  icd10AdditionalNotes?: string | null;
  riskLevel?: string;
  preventionLevel?: string | null;
  aiSuggestions?: string | null;
  selectedInterventions?: string | null;
  evaluationStatus?: string | null;
  evaluationNotes?: string | null;
  interventionEvaluations?: string | null;
  referralType?: string | null;
  referralPriority?: string | null;
  referralFacility?: string | null;
  referralSummary?: string | null;
  referralStatus?: string;
  healthHistory?: string | null;
  healthHistoryRefCode?: string | null;
  height?: string | null;
  weight?: string | null;
  bmi?: string | null;
  gravidity?: number | null;
  parity?: number | null;
  lmp?: string | null;
  aog?: string | null;
}

// ── Constants ────────────────────────────────────────────────────────────

const STORAGE_PREFIX = 'momternal-offline-consultation-';

// ── Helpers ──────────────────────────────────────────────────────────────

/** Build the localStorage key for a given tempId. */
function storageKey(tempId: string): string {
  return `${STORAGE_PREFIX}${tempId}`;
}

/**
 * Safely get all localStorage keys that belong to this store.
 */
function getStoreKeys(): string[] {
  try {
    return Object.keys(localStorage).filter((k) => k.startsWith(STORAGE_PREFIX));
  } catch {
    return [];
  }
}

// ── Public API ───────────────────────────────────────────────────────────

/**
 * Create or update an offline consultation in localStorage.
 *
 * If a consultation with the given tempId already exists, the provided data
 * fields are merged on top of it. Otherwise a new record is created.
 *
 * The storage key is `momternal-offline-consultation-{tempId}`.
 */
export function saveOfflineConsultation(
  tempId: string,
  data: Partial<OfflineConsultation>,
): OfflineConsultation {
  const now = new Date().toISOString();

  let existing: OfflineConsultation | null = null;
  try {
    const raw = localStorage.getItem(storageKey(tempId));
    if (raw) {
      existing = JSON.parse(raw) as OfflineConsultation;
    }
  } catch {
    // If we can't read, treat as new
  }

  const consultation = {
    ...(existing ?? {
      tempId,
      consultationNo: 'OFFLINE-TEMP',
      status: 'in_progress',
      stepCompleted: 0,
      createdAt: now,
    }),
    ...data,
    tempId,        // always preserve the tempId
    updatedAt: now, // always bump the timestamp
  } as OfflineConsultation;

  try {
    localStorage.setItem(storageKey(tempId), JSON.stringify(consultation));
  } catch {
    // Storage full or unavailable — silently fail
  }

  return consultation;
}

/**
 * Retrieve an offline consultation from localStorage by its tempId.
 */
export function getOfflineConsultation(tempId: string): OfflineConsultation | null {
  try {
    const raw = localStorage.getItem(storageKey(tempId));
    if (!raw) return null;
    return JSON.parse(raw) as OfflineConsultation;
  } catch {
    return null;
  }
}

/**
 * Update specific fields of an existing offline consultation.
 *
 * Returns the updated consultation, or `null` if no record with the given
 * tempId exists in localStorage.
 */
export function updateOfflineConsultation(
  tempId: string,
  updates: Partial<OfflineConsultation>,
): OfflineConsultation | null {
  const existing = getOfflineConsultation(tempId);
  if (!existing) return null;
  return saveOfflineConsultation(tempId, updates);
}

/**
 * Delete an offline consultation from localStorage.
 *
 * Returns `true` if a record was found and removed, `false` otherwise.
 */
export function deleteOfflineConsultation(tempId: string): boolean {
  const key = storageKey(tempId);
  try {
    if (localStorage.getItem(key) === null) return false;
    localStorage.removeItem(key);
    return true;
  } catch {
    return false;
  }
}

/**
 * Return all offline consultations stored in localStorage.
 */
export function getAllOfflineConsultations(): OfflineConsultation[] {
  const keys = getStoreKeys();
  const results: OfflineConsultation[] = [];

  for (const key of keys) {
    try {
      const raw = localStorage.getItem(key);
      if (!raw) continue;
      results.push(JSON.parse(raw) as OfflineConsultation);
    } catch {
      // Skip corrupted entries
    }
  }

  return results;
}

/**
 * After a successful sync, map the tempId to the real server-assigned ID.
 *
 * - Sets `realId` on the consultation record.
 * - Removes the old storage key and re-saves under a new key that includes
 *   the realId so it can still be found via `getOfflineConsultationByRealId`.
 *
 * Returns `true` on success, `false` if the consultation was not found.
 */
export function mapTempToRealId(tempId: string, realId: string): boolean {
  const consultation = getOfflineConsultation(tempId);
  if (!consultation) return false;

  consultation.realId = realId;
  consultation.updatedAt = new Date().toISOString();

  try {
    // Remove old key
    localStorage.removeItem(storageKey(tempId));

    // Save under a composite key: prefix + tempId + "::mapped::" + realId
    // This keeps the original key namespace but makes lookup by realId easy.
    const mappedKey = `${STORAGE_PREFIX}${tempId}::mapped::${realId}`;
    localStorage.setItem(mappedKey, JSON.stringify(consultation));
    return true;
  } catch {
    return false;
  }
}

/**
 * Find an offline consultation that has been synced and has a matching realId.
 */
export function getOfflineConsultationByRealId(realId: string): OfflineConsultation | null {
  const keys = getStoreKeys();

  for (const key of keys) {
    // Only check mapped keys (they contain "::mapped::")
    if (!key.includes('::mapped::')) continue;

    try {
      const raw = localStorage.getItem(key);
      if (!raw) continue;
      const consultation = JSON.parse(raw) as OfflineConsultation;
      if (consultation.realId === realId) {
        return consultation;
      }
    } catch {
      // Skip corrupted entries
    }
  }

  return null;
}

/**
 * Returns `true` if the given ID follows the offline temp ID format
 * (starts with `"offline-"`).
 */
export function isOfflineId(id: string): boolean {
  return typeof id === 'string' && id.startsWith('offline-');
}

/**
 * Returns the count of unsynced offline consultations — i.e. those that do
 * **not** yet have a `realId` assigned.
 */
export function getOfflineConsultationCount(): number {
  const all = getAllOfflineConsultations();
  return all.filter((c) => !c.realId).length;
}

/**
 * Remove all offline consultations that have been successfully synced
 * (those that have a `realId`).
 *
 * Returns the number of cleaned-up records.
 */
export function cleanupSyncedConsultations(): number {
  const keys = getStoreKeys();
  let cleaned = 0;

  for (const key of keys) {
    try {
      const raw = localStorage.getItem(key);
      if (!raw) continue;
      const consultation = JSON.parse(raw) as OfflineConsultation;
      if (consultation.realId) {
        localStorage.removeItem(key);
        cleaned++;
      }
    } catch {
      // Skip corrupted entries
    }
  }

  return cleaned;
}
