/**
 * MOMternal Offline Consultation Store
 *
 * Manages consultation data locally when the user creates or edits a consultation
 * while offline. Consultations are stored in localStorage keyed by a temp ID
 * (format: `offline-{timestamp}-{random}`).
 *
 * Features:
 * - Create / read / update / delete offline consultations
 * - Temp-to-real ID mapping after successful sync
 * - Lookup by real ID for post-sync navigation
 * - Cleanup of synced records
 * - All localStorage access wrapped in try-catch for resilience
 */

// ── Types ────────────────────────────────────────────────────────────────

export interface OfflineConsultation {
  tempId: string;              // The temp ID generated by offlineFetch
  patientId: string;           // The real patient DB ID
  patientName?: string;        // Patient name for display
  patientPatientId?: string;   // Patient's patient_id (display ID like "MOM-0001")
  nurseId: string;             // The nurse's DB ID
  nurseName?: string;          // Nurse's name for display
  createdAt: string;           // ISO timestamp
  updatedAt: string;           // ISO timestamp
  consultationNo: string;      // "OFFLINE-TEMP" placeholder
  consultationDate: string;    // ISO date string
  stepCompleted: number;       // Current wizard step
  status: string;              // "in_progress"
  realId?: string;             // Set after successful sync — the real DB consultation ID

  // All the consultation form fields (same as ConsultationData interface):
  typeOfVisit?: string | null;
  chiefComplaint?: string | null;
  subjectiveSymptoms?: string | null;
  objectiveVitals?: string | null;
  fetalHeartRate?: string | null;
  fundalHeight?: string | null;
  allergies?: string | null;
  medications?: string | null;
  physicalExam?: string | null;
  labResults?: string | null;
  notes?: string | null;
  icd10Diagnosis?: string | null;
  nandaDiagnosis?: string | null;
  nandaCode?: string | null;
  nandaName?: string | null;
  nandaRelatedTo?: string | null;
  icd10AdditionalNotes?: string | null;
  riskLevel?: string;
  preventionLevel?: string | null;
  aiSuggestions?: string | null;
  selectedInterventions?: string | null;
  evaluationStatus?: string | null;
  evaluationNotes?: string | null;
  interventionEvaluations?: string | null;
  referralType?: string | null;
  referralPriority?: string | null;
  referralFacility?: string | null;
  referralSummary?: string | null;
  referralStatus?: string;
  healthHistory?: string | null;
  healthHistoryRefCode?: string | null;
  height?: string | null;
  weight?: string | null;
  bmi?: string | null;
  gravidity?: number | null;
  parity?: number | null;
  lmp?: string | null;
  aog?: string | null;
}

// ── Constants ────────────────────────────────────────────────────────────

const STORAGE_PREFIX = 'momternal-offline-consultation-';

// ── Helpers ──────────────────────────────────────────────────────────────

/** Build the localStorage key for a given tempId. */
function storageKey(tempId: string): string {
  return `${STORAGE_PREFIX}${tempId}`;
}

/**
 * Safely get all localStorage keys that belong to this store.
 */
function getStoreKeys(): string[] {
  try {
    return Object.keys(localStorage).filter((k) => k.startsWith(STORAGE_PREFIX));
  } catch {
    return [];
  }
}

// ── Public API ───────────────────────────────────────────────────────────

/**
 * Create or update an offline consultation in localStorage.
 *
 * If a consultation with the given tempId already exists, the provided data
 * fields are merged on top of it. Otherwise a new record is created.
 *
 * The storage key is `momternal-offline-consultation-{tempId}`.
 */
export function saveOfflineConsultation(
  tempId: string,
  data: Partial<OfflineConsultation>,
): OfflineConsultation {
  const key = `${STORAGE_PREFIX}${tempId}`;
  let consultation: OfflineConsultation;

  try {
    const raw = localStorage.getItem(key);
    if (raw) {
      // Merge with existing
      consultation = JSON.parse(raw) as OfflineConsultation;
      const updates = { ...data, updatedAt: new Date().toISOString() };
      Object.entries(updates).forEach(([k, v]) => {
        if (v !== undefined) (consultation as unknown as Record<string, unknown>)[k] = v;
      });
    } else {
      // Create new with defaults
      consultation = {
        patientId: data.patientId || '',
        nurseId: data.nurseId || '',
        createdAt: data.createdAt || new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        consultationNo: data.consultationNo || 'OFFLINE-TEMP',
        consultationDate: data.consultationDate || new Date().toISOString().slice(0, 10),
        stepCompleted: data.stepCompleted ?? 0,
        status: data.status || 'in_progress',
        ...data,
        tempId, // Prevent accidental override from spread
      } as OfflineConsultation;
    }

    localStorage.setItem(key, JSON.stringify(consultation));
  } catch {
    // Storage full or unavailable — return a default object so the caller doesn't crash
    consultation = {
      tempId,
      patientId: data.patientId || '',
      nurseId: data.nurseId || '',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      consultationNo: 'OFFLINE-TEMP',
      consultationDate: new Date().toISOString().slice(0, 10),
      stepCompleted: 0,
      status: 'in_progress',
    };
  }

  return consultation;
}

/**
 * Retrieve an offline consultation from localStorage by its tempId.
 */
export function getOfflineConsultation(tempId: string): OfflineConsultation | null {
  try {
    const raw = localStorage.getItem(storageKey(tempId));
    if (!raw) return null;
    return JSON.parse(raw) as OfflineConsultation;
  } catch {
    return null;
  }
}

/**
 * Update specific fields of an existing offline consultation.
 *
 * Returns the updated consultation, or `null` if no record with the given
 * tempId exists in localStorage.
 */
export function updateOfflineConsultation(
  tempId: string,
  updates: Partial<OfflineConsultation>,
): OfflineConsultation | null {
  const existing = getOfflineConsultation(tempId);
  if (!existing) return null;
  return saveOfflineConsultation(tempId, updates);
}

/**
 * Delete an offline consultation from localStorage.
 *
 * Returns `true` if a record was found and removed, `false` otherwise.
 */
export function deleteOfflineConsultation(tempId: string): boolean {
  const key = storageKey(tempId);
  try {
    if (localStorage.getItem(key) === null) return false;
    localStorage.removeItem(key);
    return true;
  } catch {
    return false;
  }
}

/**
 * Return all offline consultations stored in localStorage.
 */
export function getAllOfflineConsultations(): OfflineConsultation[] {
  const keys = getStoreKeys();
  const results: OfflineConsultation[] = [];

  for (const key of keys) {
    try {
      const raw = localStorage.getItem(key);
      if (!raw) continue;
      results.push(JSON.parse(raw) as OfflineConsultation);
    } catch {
      // Skip corrupted entries
    }
  }

  return results;
}

/**
 * After a successful sync, map the tempId to the real server-assigned ID.
 *
 * - Sets `realId` on the consultation record.
 * - Keeps the original storage key so existing lookups still work.
 *
 * Returns `true` on success, `false` if the consultation was not found.
 */
export function mapTempToRealId(tempId: string, realId: string): boolean {
  try {
    const key = `${STORAGE_PREFIX}${tempId}`;
    const raw = localStorage.getItem(key);
    if (!raw) {
      // Try the mapped key format (for backward compat during transition)
      const mappedKey = `${STORAGE_PREFIX}${tempId}::mapped::${realId}`;
      const mappedRaw = localStorage.getItem(mappedKey);
      if (mappedRaw) return true; // Already mapped
      return false;
    }
    const consultation: OfflineConsultation = JSON.parse(raw);
    consultation.realId = realId;
    consultation.updatedAt = new Date().toISOString();
    localStorage.setItem(key, JSON.stringify(consultation));
    return true;
  } catch {
    return false;
  }
}

/**
 * Find an offline consultation that has been synced and has a matching realId.
 */
export function getOfflineConsultationByRealId(realId: string): OfflineConsultation | null {
  try {
    const all = getAllOfflineConsultations();
    return all.find(c => c.realId === realId) || null;
  } catch {
    return null;
  }
}

/**
 * Returns `true` if the given ID follows the offline temp ID format
 * (starts with `"offline-"`).
 */
export function isOfflineId(id: string): boolean {
  return typeof id === 'string' && id.startsWith('offline-');
}

/**
 * Returns the count of unsynced offline consultations — i.e. those that do
 * **not** yet have a `realId` assigned.
 */
export function getOfflineConsultationCount(): number {
  const all = getAllOfflineConsultations();
  return all.filter((c) => !c.realId).length;
}

/**
 * Remove all offline consultations that have been successfully synced
 * (those that have a `realId`).
 *
 * Returns the number of cleaned-up records.
 */
export function cleanupSyncedConsultations(): number {
  try {
    const all = getAllOfflineConsultations();
    let cleaned = 0;
    for (const consultation of all) {
      if (consultation.realId) {
        const key = `${STORAGE_PREFIX}${consultation.tempId}`;
        localStorage.removeItem(key);
        cleaned++;
      }
    }
    return cleaned;
  } catch {
    return 0;
  }
}
